### PR TITLE
Note that it is abandoned

### PR DESCRIPTION
**Pull request by pulsejet**

### CODE REVIEW

**Comment by Pesa** [comment]
@cawka ping

**Comment by cawka** [comment]
Note where? In the description on github it is already mentioned that it is OBSOLETE..

**Comment by Pesa** [comment]
In the README. At least that's what the commit does... It's easy to overlook the tiny description on the right.

Or we could just archive the repo, that's even more obvious.

**Review by cawka — APPROVED** [review]

**Comment by cawka** [comment]
Totally missed that it is a pull request and not just an issue...

**Pull request merged**
